import type { RawCategory, RawProduct } from "./clientStore";

export const INITIAL_CATEGORIES: RawCategory[] = [
  { id: "misks", nameRu: "Миски и парфюмерия", nameKz: "Мисктер мен парфюмерия", icon: "✨", order: 1 },
  { id: "health", nameRu: "Здоровье", nameKz: "Денсаулық", icon: "🌿", order: 2 },
  { id: "natural", nameRu: "Натуральные продукты", nameKz: "Табиғи өнімдер", icon: "🍯", order: 3 },
  { id: "vitamins", nameRu: "iHerb Витамины", nameKz: "iHerb витаминдері", icon: "💊", order: 4 },
  { id: "muslim", nameRu: "Для мусульман", nameKz: "Мұсылмандарға", icon: "🕋", order: 5 },
  { id: "beauty", nameRu: "Красота", nameKz: "Сұлулық", icon: "🧴", order: 6 },
  { id: "weight", nameRu: "Набор веса", nameKz: "Салмақ қосу", icon: "💪", order: 7 },
  { id: "slimming", nameRu: "Похудение", nameKz: "Арықтау", icon: "🍃", order: 8 },
  { id: "misc", nameRu: "Разное", nameKz: "Басқа", icon: "📦", order: 9 },
];

export const INITIAL_PRODUCTS: RawProduct[] = [
  {
    id: "p-black-seed-oil",
    docId: "p-black-seed-oil",
    titleRu: "Масло черного тмина «Королевское» 500 мл (El-Hawag, Египет)",
    titleKz: "Қара зере майы «Королевское» 500 мл (El-Hawag, Мысыр)",
    descriptionRu: "100% натуральное масло черного тмина первого холодного отжима. Производство Египет (завод Аль-Хавадж). Способствует укреплению иммунитета, нормализации давления, улучшению пищеварения и очищению организма.",
    descriptionKz: "100% табиғи бірінші суық сығынды қара зере майы. Мысыр елінде өндірілген (Әл-Хауадж зауыты). Иммунитетті нығайтуға, қан қысымын реттеуге көмектеседі.",
    specsRu: "Объем: 500 мл\nСтрана: Египет\nБренд: El-Hawag\nСпособ применения: 1 ч.л. утром натощак",
    specsKz: "Көлемі: 500 мл\nЕл: Мысыр\nБренді: El-Hawag",
    price: 6500,
    oldPrice: 7500,
    categoryId: "health",
    images: [
      "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80",
    ],
    inStock: true,
    isNew: false,
    isHit: true,
    isSale: true,
    sku: "MS-0101",
    createdAt: "2026-03-01T10:00:00.000Z",
  },
  {
    id: "p-al-rehab-choco-musk",
    docId: "p-al-rehab-choco-musk",
    titleRu: "Масляные духи Al-Rehab Choco Musk (6 мл, ОАЭ)",
    titleKz: "Майлы әтір Al-Rehab Choco Musk (6 мл, БӘӘ)",
    descriptionRu: "Оригинальный масляный концентрат без спирта. Неповторимый гурманский аромат горячего шоколада, ванили, корицы и белого мускуса. Стойкость до 48 часов на одежде.",
    descriptionKz: "Спиртсіз түпнұсқа майлы әтір. Ыстық шоколад, ваниль және ақ мускус хош иісі. Киімде 48 сағатқа дейін сақталады.",
    specsRu: "Объем: 6 мл\nФормат: Роллер\nСтрана: ОАЭ\nБазовые ноты: Шоколад, Ваниль, Мускус",
    specsKz: "Көлемі: 6 мл\nЕл: БӘӘ\nХош иіс: Шоколад, Ваниль",
    price: 1800,
    oldPrice: 2200,
    categoryId: "misks",
    images: [
      "https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&w=800&q=80",
    ],
    inStock: true,
    isNew: false,
    isHit: true,
    isSale: false,
    sku: "MS-0201",
    createdAt: "2026-03-02T10:00:00.000Z",
  },
  {
    id: "p-al-rehab-silver",
    docId: "p-al-rehab-silver",
    titleRu: "Масляные духи Al-Rehab Silver (6 мл, ОАЭ)",
    titleKz: "Майлы әтір Al-Rehab Silver (6 мл, БӘӘ)",
    descriptionRu: "Свежий, звонкий цитрусово-древесный аромат для мужчин и женщин. Очень похож на Silver Mountain Water. Свежесть мяты, лайма и легкий мускус.",
    descriptionKz: "Ерлер мен әйелдерге арналған балғын цитрусты-ағаш хош иісі. Мята, лайм және жеңіл мускус хош иісі.",
    specsRu: "Объем: 6 мл\nФормат: Роллер\nСтрана: ОАЭ",
    specsKz: "Көлемі: 6 мл\nЕл: БӘӘ",
    price: 1800,
    oldPrice: null,
    categoryId: "misks",
    images: [
      "https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&w=800&q=80",
    ],
    inStock: true,
    isNew: false,
    isHit: true,
    isSale: false,
    sku: "MS-0202",
    createdAt: "2026-03-03T10:00:00.000Z",
  },
  {
    id: "p-dates-ajwa",
    docId: "p-dates-ajwa",
    titleRu: "Финики Аджва из Медины (Madinah Ajwa Dates, 500 г)",
    titleKz: "Мәдинадан Аджва құрмасы (500 г)",
    descriptionRu: "Благословенные финики сорта Аджва, выращенные в Медине. Мягкие, умеренно сладкие, богатые калием, магнием и железом. Согласно сунне, приносят пользу и благословение.",
    descriptionKz: "Мәдина қаласынан келген қасиетті Аджва құрмасы. Жұмсақ, калий мен темірге бай.",
    specsRu: "Вес: 500 г\nСорт: Аджва (Ajwa)\nСтрана: Саудовская Аравия",
    specsKz: "Салмағы: 500 г\nСұрпы: Аджва\nЕл: Сауд Арабиясы",
    price: 5500,
    oldPrice: 6500,
    categoryId: "natural",
    images: [
      "https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=800&q=80",
    ],
    inStock: true,
    isNew: true,
    isHit: true,
    isSale: true,
    sku: "MS-0301",
    createdAt: "2026-03-04T10:00:00.000Z",
  },
  {
    id: "p-royal-honey-vip",
    docId: "p-royal-honey-vip",
    titleRu: "Королевский мед для мужчин Royal Honey VIP (12 саше)",
    titleKz: "Ерлерге арналған Royal Honey VIP корольдік балы (12 саше)",
    descriptionRu: "Натуральный горный мед с добавлением маточного молочка, корня женьшеня и экстракта эврикомы длиннолистной (Тонгкат Али). Повышает энергию, тонус и выносливость.",
    descriptionKz: "Аналық сүт, женьшень және тонгкат али қосылған табиғи тау балы. Күш-қуат береді.",
    specsRu: "Количество: 12 саше по 20 г\nСтрана: Малайзия\nНазначение: Энергия и тонус",
    specsKz: "Саны: 12 саше\nЕл: Малайзия",
    price: 8500,
    oldPrice: 10000,
    categoryId: "natural",
    images: [
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80",
    ],
    inStock: true,
    isNew: true,
    isHit: true,
    isSale: true,
    sku: "MS-0302",
    createdAt: "2026-03-05T10:00:00.000Z",
  },
  {
    id: "p-jaynamaz-ortho",
    docId: "p-jaynamaz-ortho",
    titleRu: "Ортопедический мягкий жайнамаз с эффектом памяти (Турция)",
    titleKz: "Ортопедиялық жұмсақ жайнамаз (Түркия)",
    descriptionRu: "Премиальный молитвенный коврик с ортопедическим наполнителем Memory Foam (толщина 2.5 см). Снижает нагрузку на колени и суставы во время суджуда. Не скользит на полу.",
    descriptionKz: "Memory Foam толтырғышы бар премиум жайнамаз (қалыңдығы 2.5 см). Тізеге түсетін салмақты жеңілдетеді.",
    specsRu: "Размер: 120 × 70 см\nТолщина: 2.5 см\nМатериал: Велюр, Memory Foam\nСтрана: Турция",
    specsKz: "Өлшемі: 120 × 70 см\nҚалыңдығы: 2.5 см\nЕл: Түркия",
    price: 12500,
    oldPrice: 15000,
    categoryId: "muslim",
    images: [
      "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80",
    ],
    inStock: true,
    isNew: true,
    isHit: true,
    isSale: false,
    sku: "MS-0401",
    createdAt: "2026-03-06T10:00:00.000Z",
  },
  {
    id: "p-zamzam-water",
    docId: "p-zamzam-water",
    titleRu: "Вода Зам-Зам 5 литров (Оригинал из Мекки, Саудовская Аравия)",
    titleKz: "Зәм-Зәм суы 5 литр (Түпнұсқа, Мекке)",
    descriptionRu: "Оригинальная благословенная вода Замзам в запечатанной канистре 5 л со штрихкодом завода в Мекке. Высокая минерализация и целебные свойства.",
    descriptionKz: "Меккедегі зауыттан тікелей келген түпнұсқа 5 литрлік Зәмзәм суы.",
    specsRu: "Объем: 5 литров\nСтрана: Саудовская Аравия\nУпаковка: Заводская канистра с пломбой",
    specsKz: "Көлемі: 5 л\nЕл: Сауд Арабиясы",
    price: 9000,
    oldPrice: 11000,
    categoryId: "muslim",
    images: [
      "https://images.unsplash.com/photo-1548839140-29a749e1bc4e?auto=format&fit=crop&w=800&q=80",
    ],
    inStock: true,
    isNew: false,
    isHit: true,
    isSale: true,
    sku: "MS-0402",
    createdAt: "2026-03-07T10:00:00.000Z",
  },
  {
    id: "p-collagen-california",
    docId: "p-collagen-california",
    titleRu: "Морской гидролизованный коллаген California Gold Nutrition (464 г)",
    titleKz: "California Gold Nutrition теңіз коллагені (464 г)",
    descriptionRu: "Пептиды гидролизованного морского коллагена с гиалуроновой кислотой и витамином С. Способствует омоложению кожи, укреплению волос, ногтей и суставов. Халяль сертификат.",
    descriptionKz: "Гиалурон қышқылы және С дәрумені бар теңіз коллагені. Тері, шаш және буындарды нығайтады.",
    specsRu: "Вес: 464 г\nПорций: ~90\nФорма: Порошок\nСтрана: США",
    specsKz: "Салмағы: 464 г\nЕл: АҚШ",
    price: 14000,
    oldPrice: 16500,
    categoryId: "vitamins",
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80",
    ],
    inStock: true,
    isNew: false,
    isHit: true,
    isSale: true,
    sku: "MS-0501",
    createdAt: "2026-03-08T10:00:00.000Z",
  },
  {
    id: "p-omega-3-fish-oil",
    docId: "p-omega-3-fish-oil",
    titleRu: "Омега-3 премиальный рыбий жир Now Foods (200 капсул)",
    titleKz: "Now Foods Омега-3 балық майы (200 капсула)",
    descriptionRu: "Высокоочищенный концентрат рыбьего жира без запаха и привкуса рыбы. Поддерживает здоровье сердца, сосудов, мозга и глаз. Капсулы из халяльного говяжьего желатина.",
    descriptionKz: "Жүрек, ми және қан тамырларына арналған жоғары сапалы Омега-3 балық майы.",
    specsRu: "Количество: 200 капсул\nEPA: 360 мг, DHA: 240 мг на порцию\nСтрана: США",
    specsKz: "Саны: 200 капсула\nЕл: АҚШ",
    price: 8200,
    oldPrice: 9500,
    categoryId: "vitamins",
    images: [
      "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=800&q=80",
    ],
    inStock: true,
    isNew: true,
    isHit: false,
    isSale: false,
    sku: "MS-0502",
    createdAt: "2026-03-09T10:00:00.000Z",
  },
  {
    id: "p-miswak-sewak",
    docId: "p-miswak-sewak",
    titleRu: "Мисвак (сивaк) натуральный Al Falah в герметичной упаковке",
    titleKz: "Табиғи мисуак (сиуак) Al Falah",
    descriptionRu: "Традиционная натуральная зубная щетка из корней дерева Арак (Salvadora persica). Обладает антисептическим действием, укрепляет десны, отбеливает зубы и освежает дыхание.",
    descriptionKz: "Арақ ағашынан жасалған табиғи тіс тазалағыш. Тіс пен қызыл иекті қатайтады.",
    specsRu: "Тип: Натуральная щетка\nУпаковка: Вакуумная\nСтрана: Пакистан",
    specsKz: "Түрі: Табиғи щетка\nЕл: Пәкістан",
    price: 800,
    oldPrice: 1000,
    categoryId: "beauty",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80",
    ],
    inStock: true,
    isNew: false,
    isHit: false,
    isSale: true,
    sku: "MS-0601",
    createdAt: "2026-03-10T10:00:00.000Z",
  },
  {
    id: "p-samyun-wan",
    docId: "p-samyun-wan",
    titleRu: "Капсулы для набора массы Samyun Wan (Самюн Ван, 20 капсул)",
    titleKz: "Салмақ қосуға арналған капсулалар Samyun Wan (20 капсула)",
    descriptionRu: "Популярный растительный комплекс для улучшения аппетита, ускорения обмена веществ и набора качественного веса. Способствует росту мышечной массы и восстановлению сил.",
    descriptionKz: "Тәбетті арттыруға және табиғи салмақ қосуға арналған шөптер кешені.",
    specsRu: "Количество: 20 капсул\nНазначение: Набор веса, аппетит\nСтрана: Индонезия",
    specsKz: "Саны: 20 капсула\nЕл: Индонезия",
    price: 3800,
    oldPrice: 4500,
    categoryId: "weight",
    images: [
      "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=800&q=80",
    ],
    inStock: true,
    isNew: true,
    isHit: true,
    isSale: false,
    sku: "MS-0701",
    createdAt: "2026-03-11T10:00:00.000Z",
  },
  {
    id: "p-black-seed-soap",
    docId: "p-black-seed-soap",
    titleRu: "Натуральное мыло с черным тмином (125 г, Египет)",
    titleKz: "Қара зере қосылған табиғи сабын (125 г, Мысыр)",
    descriptionRu: "Лечебное косметическое мыло на основе масла черного тмина. Очищает поры, борется с высыпаниями и акне, успокаивает раздраженную кожу и питает витаминами.",
    descriptionKz: "Қара зере майынан жасалған емдік сабын. Бет терісін тазартады және нәрлендіреді.",
    specsRu: "Вес: 125 г\nДействие: Очищение, антисептик\nСтрана: Египет",
    specsKz: "Салмағы: 125 г\nЕл: Мысыр",
    price: 1200,
    oldPrice: null,
    categoryId: "beauty",
    images: [
      "https://images.unsplash.com/photo-1607006314644-8d96b9f1d072?auto=format&fit=crop&w=800&q=80",
    ],
    inStock: true,
    isNew: false,
    isHit: false,
    isSale: false,
    sku: "MS-0602",
    createdAt: "2026-03-12T10:00:00.000Z",
  },
];
